# Generated by Django 4.2.3 on 2023-07-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MK', 'Milk'), ('BM', 'Buttermilk'), ('FM', 'Freshmilk'), ('MS', 'Milkshake'), ('GH', 'Ghee'), ('YG', 'Yorghutplain'), ('CH', 'Cheese'), ('IC', 'Ice-cream')], max_length=2),
        ),
    ]
